decidim-admin-0.20.0/config/routes.rb
# frozen_string_literal: true

Decidim::Admin::Engine.routes.draw do
  constraints(->(request) { Decidim::Admin::OrganizationDashboardConstraint.new(request).matches? }) do
    resource :organization, only: [:edit, :update], controller: "organization" do
      resource :appearance, only: [:edit, :update], controller: "organization_appearance"
      resource :homepage, only: [:edit, :update], controller: "organization_homepage" do
        resources :content_blocks, only: [:edit, :update], controller: "organization_homepage_content_blocks"
      end

      member do
        get :users
      end
    end

    Decidim.participatory_space_manifests.each do |manifest|
      mount manifest.context(:admin).engine, at: "/", as: "decidim_admin_#{manifest.name}"
    end

    resources :static_pages
    resources :static_page_topics, except: [:index]
    resources :scope_types, except: [:show]
    resources :scopes, except: [:show] do
      resources :scopes, except: [:show]
    end
    resources :logs, only: [:index]
    resources :area_types, except: [:show]
    resources :areas, except: [:show]

    resources :authorization_workflows, only: :index

    Decidim.authorization_admin_engines.each do |manifest|
      mount manifest.admin_engine, at: "/#{manifest.name}", as: "decidim_admin_#{manifest.name}"
    end

    resources :users, except: [:edit, :update], controller: "users" do
      member do
        post :resend_invitation, to: "users#resend_invitation"
      end
    end

    resources :officializations, only: [:new, :create, :index, :destroy, :richiesta], param: :user_id
    get 'officializations/richiesta' => 'officializations#richiesta'
    get 'officializations/richiesta/delete' => 'officializations#cancella'
    get 'officializations/disabilita' => 'officializations#disabilita'
    get 'officializations/disabilita/disable' => 'officializations#disable_user' 

    resources :impersonatable_users, only: [:index] do
      resources :promotions, controller: "managed_users/promotions", only: [:new, :create]
      resources :impersonation_logs, controller: "managed_users/impersonation_logs", only: [:index]
      resources :impersonations, controller: "impersonations", only: [:new, :create] do
        collection do
          post :close_session
        end
      end
    end

    resources :newsletters do
      member do
        get :preview
        get :select_recipients_to_deliver
        post :deliver
      end
    end

    resources :user_groups, only: [:index] do
      member do
        put :verify
        put :reject
      end
      collection do
        resource :user_groups_csv_verification, only: [:new, :create], path: "csv_verification"
      end
    end

    resource :help_sections, only: [:show, :update]

    resources :oauth_applications

    root to: "dashboard#show"
  end
end

decidim-admin-0.20.0/app/controllers/decidim/admin/organization_appearance_controller.rb
# frozen_string_literal: true

module Decidim
  module Admin
    # Controller that allows managing the appearance of the organization.
    class OrganizationAppearanceController < Decidim::Admin::ApplicationController
      layout "decidim/admin/settings"
     # skip_before_action :verify_authenticity_token
      def edit
        enforce_permission_to :update, :organization, organization: current_organization
        @form = form(OrganizationAppearanceForm).from_model(current_organization)
      end

      def update
        enforce_permission_to :update, :organization, organization: current_organization
        @form = form(OrganizationAppearanceForm).from_params(params)

        UpdateOrganizationAppearance.call(current_organization, @form) do
          on(:ok) do
            flash[:notice] = I18n.t("organization.update.success", scope: "decidim.admin")
            redirect_to edit_organization_appearance_path
          end

          on(:invalid) do
            flash.now[:alert] = I18n.t("organization.update.error", scope: "decidim.admin")
            render :edit
          end
        end
      end
    end
  end
end

decidim-admin-0.20.0/app/views/decidim/admin/organization_appearance/_form.html.erb
<%= javascript_include_tag "decidim/slug_form" %>

<div class="card">
  <div class="card-divider">
    <h2 class="card-title"><%= t ".homepage_appearance_title" %></h2>
  </div>
  <div class="card-section">
    <div class="row column">
      <%= form.check_box :show_statistics %>
    </div>

    <div class="row column">
      <%= form.translated :editor, :description %>
    </div>

    <div class="row">
      <div class="columns xlarge-6 slug">
        <%= form.text_field :cta_button_path %>
        <p class="help-text"><%== t(".cta_button_path_help", url: decidim_form_slug_url("", form.object.cta_button_path)) %></p>
      </div>

      <div class="columns xlarge-6">
        <%= form.translated :text_field, :cta_button_text %>
        <p class="help-text"><%= t(".cta_button_text_help") %></p>
      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-divider">
    <h2 class="card-title"><%= t ".homepage_highlighted_content_banner_title" %></h2>
  </div>
  <div class="card-section">
    <div class="row column">
      <%= form.check_box :highlighted_content_banner_enabled %>
    </div>

    <div class="row column">
      <%= form.translated :text_area, :highlighted_content_banner_title %>
    </div>

    <div class="row column">
      <%= form.translated :editor, :highlighted_content_banner_short_description %>
    </div>

    <div class="row column">
      <%= form.translated :text_area, :highlighted_content_banner_action_title %>
    </div>

    <div class="row column">
      <%= form.translated :text_area, :highlighted_content_banner_action_subtitle %>
    </div>

    <div class="row column">
      <%= form.url_field :highlighted_content_banner_action_url %>
    </div>

    <div class="row">
      <div class="columns xlarge-6">
        <%= form.upload :highlighted_content_banner_image %>
      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-divider">
    <h2 class="card-title"><%= t ".omnipresent_banner_appearance_title" %></h2>
  </div>
  <div class="card-section">
    <div class="row column">
      <%= form.check_box :enable_omnipresent_banner %>
    </div>

    <div class="row column">
      <%= form.translated :text_field, :omnipresent_banner_title %>
    </div>

    <div class="row column">
      <%= form.translated :text_field, :omnipresent_banner_short_description %>
    </div>

    <div class="row column">
      <%= form.url_field :omnipresent_banner_url %>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-divider">
    <h2 class="card-title"><%= t ".layout_appearance_title" %></h2>
  </div>
  <div class="card-section">
    <div class="row">
      <div class="columns xlarge-6">
        <%= form.upload :logo %>
      </div>

      <div class="columns xlarge-6">
        <%= form.upload :favicon %>
      </div>
    </div>

    <div class="row">
      <div class="columns xlarge-6">
        <%= form.upload :official_img_header %>
      </div>

      <div class="columns xlarge-6">
        <%= form.upload :official_img_footer %>
      </div>
    </div>

    <div class="row">
      <div class="columns xlarge-6">
        <%= form.text_field :official_url %>
      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-divider">
    <h2 class="card-title"><%= t ".colors_title" %></h2>
  </div>
  <div class="card-section">
    <div class="row">
      <div class="columns xlarge-6">
        <%= form.color_field :primary_color, value: current_organization.colors["primary"] %>
      </div>

      <div class="columns xlarge-6">
        <%= form.color_field :secondary_color, value: current_organization.colors["secondary"] %>
      </div>
    </div>

    <div class="row">
      <div class="columns xlarge-6">
        <%= form.color_field :success_color, value: current_organization.colors["success"] %>
      </div>

      <div class="columns xlarge-6">
        <%= form.color_field :warning_color, value: current_organization.colors["warning"] %>
      </div>
    </div>

    <div class="row">
      <div class="columns xlarge-6">
        <%= form.color_field :alert_color, value: current_organization.colors["alert"] %>
      </div>
    </div>

    <% if Decidim.enable_html_header_snippets %>
      <div class="row column">
        <%= form.text_area :header_snippets %>
        <p class="help-text"><%= t(".header_snippets_help") %></p>
      </div>
    <% end %>
  </div>
</div>

decidim-admin-0.20.0/app/views/decidim/admin/organization_appearance/edit.html.erb
<%= decidim_form_for(@form, html: { class: "form edit_organization_appearance" }, url: organization_appearance_path, method: :put) do |f| %>
  <%= render partial: "form", object: f %>
  <div class="button--double form-general-submit">
    <%= f.submit t(".update") %>
  </div>
<% end %>