decidim-admin-0.20.0/config/routes.rb
# frozen_string_literal: true

Decidim::Admin::Engine.routes.draw do
  constraints(->(request) { Decidim::Admin::OrganizationDashboardConstraint.new(request).matches? }) do
    resource :organization, only: [:edit, :update], controller: "organization" do
      resource :appearance, only: [:edit, :update], controller: "organization_appearance"
      resource :homepage, only: [:edit, :update], controller: "organization_homepage" do
        resources :content_blocks, only: [:edit, :update], controller: "organization_homepage_content_blocks"
      end

      member do
        get :users
      end
    end

    Decidim.participatory_space_manifests.each do |manifest|
      mount manifest.context(:admin).engine, at: "/", as: "decidim_admin_#{manifest.name}"
    end

    resources :static_pages
    resources :static_page_topics, except: [:index]
    resources :scope_types, except: [:show]
    resources :scopes, except: [:show] do
      resources :scopes, except: [:show]
    end
    resources :logs, only: [:index]
    resources :area_types, except: [:show]
    resources :areas, except: [:show]

    resources :authorization_workflows, only: :index

    Decidim.authorization_admin_engines.each do |manifest|
      mount manifest.admin_engine, at: "/#{manifest.name}", as: "decidim_admin_#{manifest.name}"
    end

    resources :users, except: [:edit, :update], controller: "users" do
      member do
        post :resend_invitation, to: "users#resend_invitation"
      end
    end

    resources :officializations, only: [:new, :create, :index, :destroy, :richiesta], param: :user_id
    get 'officializations/richiesta' => 'officializations#richiesta'
    get 'officializations/richiesta/delete' => 'officializations#cancella'
    get 'officializations/disabilita' => 'officializations#disabilita'
    get 'officializations/disabilita/disable' => 'officializations#disable_user' 

    resources :impersonatable_users, only: [:index] do
      resources :promotions, controller: "managed_users/promotions", only: [:new, :create]
      resources :impersonation_logs, controller: "managed_users/impersonation_logs", only: [:index]
      resources :impersonations, controller: "impersonations", only: [:new, :create] do
        collection do
          post :close_session
        end
      end
    end

    resources :newsletters do
      member do
        get :preview
        get :select_recipients_to_deliver
        post :deliver
      end
    end

    resources :user_groups, only: [:index] do
      member do
        put :verify
        put :reject
      end
      collection do
        resource :user_groups_csv_verification, only: [:new, :create], path: "csv_verification"
      end
    end

    resource :help_sections, only: [:show, :update]

    resources :oauth_applications

    root to: "dashboard#show"
  end
end

decidim-admin-0.20.0/app/controllers/concerns/decidim/admin/user_groups.rb
# frozen_string_literal: true

require "active_support/concern"

module Decidim
  module Admin
    # The UserGroups concern must be included in all controllers related
    # to UserGroups feature. It adds a method to enforce that the feature
    # is enabled.
    module UserGroups
      extend ActiveSupport::Concern

      included do
        delegate :user_groups_enabled?, to: :current_organization

        helper_method :user_groups_enabled?
      end

      def enforce_user_groups_enabled
        raise Decidim::ActionForbidden unless current_organization.user_groups_enabled?
      end
    end
  end
end

decidim-admin-0.20.0/app/controllers/decidim/admin/user_groups_controller.rb
# frozen_string_literal: true

module Decidim
  module Admin
    # Controller that allows managing user groups at the admin panel.
    #
    class UserGroupsController < Decidim::Admin::ApplicationController
      include UserGroups

      before_action :enforce_user_groups_enabled

      layout "decidim/admin/users"

      def index
        enforce_permission_to :index, :user_group
        @query = params[:q]
        @state = params[:state]

        @user_groups = Decidim::Admin::UserGroupsEvaluation.for(collection, @query, @state)
                                                           .page(params[:page]).per(15)
      end

      def verify
        @user_group = collection.find(params[:id])
        enforce_permission_to :verify, :user_group, user_group: @user_group

        VerifyUserGroup.call(@user_group, current_user) do
          on(:ok) do
            flash[:notice] = I18n.t("user_group.verify.success", scope: "decidim.admin")
            redirect_back(fallback_location: decidim_admin.user_groups_path)
          end

          on(:invalid) do
            flash[:alert] = I18n.t("user_group.verify.invalid", scope: "decidim.admin")
            redirect_back(fallback_location: decidim_admin.user_groups_path)
          end
        end
      end

      def reject
        @user_group = collection.find(params[:id])
        enforce_permission_to :reject, :user_group, user_group: @user_group

        RejectUserGroup.call(@user_group, current_user) do
          on(:ok) do
            flash[:notice] = I18n.t("user_group.reject.success", scope: "decidim.admin")
            redirect_back(fallback_location: decidim_admin.user_groups_path)
          end

          on(:invalid) do
            flash[:alert] = I18n.t("user_group.reject.invalid", scope: "decidim.admin")
            redirect_back(fallback_location: decidim_admin.user_groups_path)
          end
        end
      end

      private

      def collection
        UserGroup
          .includes(:memberships)
          .where(decidim_user_group_memberships: { decidim_user_id: current_organization.users })
      end
    end
  end
end

decidim-admin-0.20.0/app/views/decidim/admin/user_groups/index.html.erb
<div class="filters row">
  <div class="column medium-3">
    <span class="dropdown-menu-inverted_label"><%= t(".filter_by") %> :</span>
    <ul class="dropdown menu dropdown-inverted" data-dropdown-menu data-close-on-click-inside="false">
        <li class="is-dropdown-submenu-parent">
          <a href="#">
          <% if @state.present? %>
            <%= t(".filter.#{@state}") %>
          <% else %>
            <%= t(".filter.all") %>
          <% end %>
          </a>
          <ul class="menu is-dropdown-submenu">
            <li><%= link_to t(".filter.pending"), url_for(state: "pending", q: @query) %></li>
            <li><%= link_to t(".filter.rejected"), url_for(state: "rejected", q: @query) %></li>
            <li><%= link_to t(".filter.verified"), url_for(state: "verified", q: @query) %></li>
            <li><%= link_to t(".filter.all"), url_for(q: @query) %></li>
          </ul>
        </li>
      </ul>
  </div>
  <div class="column medium-4">
    <%= form_tag "", method: :get do %>
      <div class="filters__search">
        <div class="input-group">
          <%= search_field_tag :q, @query,label: false, class: "input-group-field", placeholder: t(".search") %>
          <%= hidden_field_tag :state, @state %>
          <div class="input-group-button">
            <button type="submit" class="button button--muted">
              <%= icon "magnifying-glass", aria_label: t(".search") %>
            </button>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="card" id='user-groups'>
  <div class="card-divider">
    <h2 class="card-title">
      <%= t "decidim.admin.titles.user_groups" %>
      <%= link_to t(".verify_via_csv"), new_user_groups_csv_verification_path, class: "button tiny button--title" %>
    </h2>
  </div>
  <div class="card-section">
    <div class="table-scroll">
      <table class="table-list">
        <thead>
          <tr>
            <th><%= t("models.user_group.fields.name", scope: "decidim.admin") %></th>
            <th><%= t("models.user_group.fields.document_number", scope: "decidim.admin") %></th>
            <th><%= t("models.user_group.fields.phone", scope: "decidim.admin") %></th>
            <th><%= t("models.user_group.fields.users_count", scope: "decidim.admin") %></th>
            <th><%= t("models.user_group.fields.created_at", scope: "decidim.admin") %></th>
            <th><%= t("models.user_group.fields.state", scope: "decidim.admin") %></th>
            <th><%= t("models.user_group.fields.actions", scope: "decidim.admin") %></th>
          </tr>
        </thead>
        <tbody>
          <% @user_groups.each do |user_group| %>
            <tr data-user-group-id="<%= user_group.id %>">
              <td><%= user_group.name %></td>
              <td><%= user_group.document_number %></td>
              <td><%= user_group.phone %></td>
              <td><%= user_group.users.size %></td>
              <td><%= l user_group.created_at, format: :short %></td>
              <td>
              <% if user_group.verified? %>
                <%= t(".state.verified") %>
              <% end %>
              <% if user_group.rejected? %>
                <%= t(".state.rejected") %>
              <% end %>
              <% if user_group.pending? %>
                <%= t(".state.pending") %>
              <% end %>
              </td>
              <td class="table-list__actions">
                <% if allowed_to?(:verify, :user_group, user_group: user_group) %>
                  <% if !user_group.verified? %>
                    <%= icon_link_to "circle-check", decidim_admin.verify_user_group_path(user_group), t("actions.verify", scope: "decidim.admin"), method: :put, class: "action-icon--verify" %>
                  <% else %>
                    <%= icon "circle-check", class: "action-icon action-icon--disabled" %>
                  <% end %>
                <% end %>

                <% if allowed_to?(:reject, :user_group, user_group: user_group) %>
                  <% if !user_group.rejected? %>
                    <%= icon_link_to "circle-x", decidim_admin.reject_user_group_path(user_group), t("actions.reject", scope: "decidim.admin"), method: :put, class: "action-icon--reject" %>
                  <% else %>
                    <%= icon "circle-x", class: "action-icon action-icon--disabled" %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @user_groups, theme: "decidim" %>
    </div>
  </div>
</div>